=== tarcisiorocha/highframe/adl.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Este é o nosso nó principal -->
<xs:element name="architecture"> 
    <xs:complexType>
        <!-- Determina que os elementos a seguir devem aparecer nesta mesma ordem -->
        <xs:sequence>
			<xs:element name="subarchitecture" maxOccurs="unbounded">
			    <!-- Define um tipo formado por outros elementos --> 
			    <xs:complexType>
			        <!-- Determina que os elementos a seguir devem aparecer nesta mesma ordem -->
			        <xs:sequence>
			            <!-- Define que o tipo "componente" pode ocorrer N vezes (unbounded = sem limite)-->
			            <xs:element name="component" maxOccurs="unbounded">
			                <!-- Define que "componente" é formado por outros elementos -->
			                <xs:complexType>
			                    <!-- Os itens de "componente" devem aparecer nessa ordem -->
			                    <xs:sequence>
			                        <!-- Define que o elemento "interfacesprovidas" não é obrigatório mas pode aparecer N vezes -->
			                        <xs:element name="providedinterface"  minOccurs="0" maxOccurs="unbounded">
			                          <xs:complexType mixed="true">  
			                             <xs:attribute name="idinterface" type="xs:string" use="required"/>  
                             			 <xs:attribute name="name" type="xs:string" use="required"/>  
                             			 <xs:attribute name="signature" type="xs:string" use="required"/>  
                              		  </xs:complexType>  
			                        </xs:element>			                        
			                        <!-- Define que o elemento "interfacesrequeridas" não é obrigatório mas pode aparecer N vezes -->
			                        <xs:element name="requiredinterface" minOccurs="0" maxOccurs="unbounded">
			                          <xs:complexType mixed="true">  
			                             <xs:attribute name="idinterface" type="xs:string" use="required"/>  
                             			 <xs:attribute name="name" type="xs:string" use="required"/>  
                             			 <xs:attribute name="signature" type="xs:string" use="required"/>  
                            		  </xs:complexType> 
			                        </xs:element>			                        
			                    </xs:sequence>
			                    <xs:attribute name="id" type="xs:string"/>
			                    <xs:attribute name="name" type="xs:string"/>
			                </xs:complexType>
			            </xs:element>
			            <xs:element name="binding" minOccurs="0" maxOccurs="unbounded">
			               <xs:complexType mixed="true">  
                              <xs:attribute name="clientcomponent" type="xs:string" use="required"/>  
                              <xs:attribute name="clientinterface" type="xs:string" use="required"/>  
                              <xs:attribute name="servercomponent" type="xs:string" use="required"/>
                              <xs:attribute name="serverinterface" type="xs:string" use="required"/>
                           </xs:complexType> 
			            </xs:element>
			            <xs:element name="exportedinterface" maxOccurs="unbounded">
					       <xs:complexType mixed="true">  
				               <xs:attribute name="idinterface" type="xs:string" use="required"/>				            
				           </xs:complexType>  
				   		</xs:element>	        
			        </xs:sequence>
			        <xs:attribute name="idsubarchitecture" type="xs:string"/>
			        <xs:attribute name="name" type="xs:string"/>		
			        		        
			    </xs:complexType>
			     
			</xs:element>
	
	   
		</xs:sequence>
	  </xs:complexType>
			    
	</xs:element>
   
</xs:schema>

=== tarcisiorocha/highframe/Data.xml
<?xml version="1.0" encoding="UTF-8"?>

<architecture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="adl.xsd">
<!-- ** Subarquiteturas InÃ­cio -->
<subarchitecture idsubarchitecture="subarc1" name="Subarc1">
<!-- **** Componentes  -->
  <component id="clientImpl" name="br.teste.ClientImpl" >
    <providedinterface idinterface="c.ip1" name="r" signature="java.lang.Runnable" ></providedinterface>
    <requiredinterface idinterface="c.ir1" name="s" signature="br.teste.Service"></requiredinterface>
<!--     <requiredinterface idinterface="c.ir2" name="s2" signature="br.teste.Service"></requiredinterface> -->
<!--     <requiredinterface idinterface="c.ir3" name="s3" signature="br.teste.Service"></requiredinterface> -->
  </component>
  
  <component id="serverImpl" name="br.teste.ServerImpl" >
    <providedinterface idinterface="s.ip1" name="r" signature="br.teste.Service" ></providedinterface>    
  </component>
<!-- **** Bindings  -->
  <binding clientcomponent="clientImpl" clientinterface="c.ir1" servercomponent="serverImpl" serverinterface="s.ip1"></binding>
<!-- **** Interfaces Exportadas  -->
  <exportedinterface idinterface="s.ip1" ></exportedinterface>  
</subarchitecture>
<!-- Subarquiteturas Fim -->
</architecture>

=== tarcisiorocha/highframe/received/unzipped/frontend.xml
<architecture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="adl.xsd">  <subarchitecture idsubarchitecture="frontend">
    <component id="comp1" name="comanche.fraclet.Receiver">
      <providedinterface idinterface="id1" name="r" signature="highframe.core.Runner" />
      <requiredinterface idinterface="id2" name="s" signature="comanche.fraclet.IScheduler" />
      <requiredinterface idinterface="id3" name="ia" signature="comanche.fraclet.IAnalyzer" />
    </component>
    <component id="comp2" name="comanche.fraclet.Scheduler">
      <providedinterface idinterface="id4" name="s" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp3" name="comanche.fraclet.Scheduler2">
      <providedinterface idinterface="" name="s2" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp4" name="comanche.fraclet.Scheduler3">
      <providedinterface idinterface="" name="s3" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp5" name="comanche.fraclet.Scheduler4">
      <providedinterface idinterface="" name="s4" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp6" name="comanche.fraclet.Scheduler5">
      <providedinterface idinterface="" name="s5" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp7" name="comanche.fraclet.Scheduler6">
      <providedinterface idinterface="" name="s6" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp8" name="comanche.fraclet.Scheduler7">
      <providedinterface idinterface="" name="s7" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp9" name="comanche.fraclet.Scheduler8">
      <providedinterface idinterface="" name="s8" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp10" name="comanche.fraclet.Scheduler9">
      <providedinterface idinterface="" name="s9" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp11" name="comanche.fraclet.Scheduler10">
      <providedinterface idinterface="" name="s10" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp12" name="comanche.fraclet.Scheduler11">
      <providedinterface idinterface="" name="s11" signature="comanche.fraclet.IScheduler" />
    </component>
    <component id="comp13" name="comanche.fraclet.Scheduler12">
      <providedinterface idinterface="" name="s12" signature="comanche.fraclet.IScheduler" />
    </component>
    <binding clientcomponent="comp1" clientinterface="id2" servercomponent="comp2" serverinterface="id4" />
    <exportedinterface idinterface="id3" />
  </subarchitecture>
</architecture>

=== tarcisiorocha/highframe/generated/backend.xml
<architecture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="adl.xsd">  <subarchitecture idsubarchitecture="backend">
    <component id="comp1" name="comanche.fraclet.Analyzer">
      <providedinterface idinterface="id5" name="a" signature="comanche.fraclet.IAnalyzer" />
      <requiredinterface idinterface="id6" name="id" signature="comanche.fraclet.IDispatcher" />
      <requiredinterface idinterface="id7" name="l" signature="comanche.fraclet.ILogger" />
    </component>
    <component id="comp2" name="comanche.fraclet.Logger">
      <providedinterface idinterface="id8" name="l" signature="comanche.fraclet.ILogger" />
    </component>
    <component id="comp3" name="comanche.fraclet.Dispatcher">
      <providedinterface idinterface="id9" name="id" signature="comanche.fraclet.IDispatcher" />
      <requiredinterface idinterface="id10" name="ifh" signature="comanche.fraclet.IFileHandler" />
      <requiredinterface idinterface="id11" name="ieh" signature="comanche.fraclet.IErrorHandler" />
    </component>
    <component id="comp4" name="comanche.fraclet.FileHandler">
      <providedinterface idinterface="id12" name="f" signature="comanche.fraclet.IFileHandler" />
    </component>
    <component id="comp5" name="comanche.fraclet.ErrorHandler">
      <providedinterface idinterface="id13" name="e" signature="comanche.fraclet.IErrorHandler" />
    </component>
    <component id="comp6" name="comanche.fraclet.Logger2">
      <providedinterface idinterface="" name="l2" signature="comanche.fraclet.ILogger" />
    </component>
    <component id="comp7" name="comanche.fraclet.Logger3">
      <providedinterface idinterface="" name="l3" signature="comanche.fraclet.ILogger" />
    </component>
    <component id="comp8" name="comanche.fraclet.Logger4">
      <providedinterface idinterface="" name="l4" signature="comanche.fraclet.ILogger" />
    </component>
    <component id="comp9" name="comanche.fraclet.Logger5">
      <providedinterface idinterface="" name="l5" signature="comanche.fraclet.ILogger" />
    </component>
    <component id="comp10" name="comanche.fraclet.Logger6">
      <providedinterface idinterface="" name="l6" signature="comanche.fraclet.ILogger" />
    </component>
    <component id="comp11" name="comanche.fraclet.Logger7">
      <providedinterface idinterface="" name="l7" signature="comanche.fraclet.ILogger" />
    </component>
    <component id="comp12" name="comanche.fraclet.Logger8">
      <providedinterface idinterface="" name="l8" signature="comanche.fraclet.ILogger" />
    </component>
    <binding clientcomponent="comp1" clientinterface="id7" servercomponent="comp2" serverinterface="id8" />
    <binding clientcomponent="comp1" clientinterface="id6" servercomponent="comp3" serverinterface="id9" />
    <binding clientcomponent="comp3" clientinterface="id10" servercomponent="comp4" serverinterface="id12" />
    <binding clientcomponent="comp3" clientinterface="id11" servercomponent="comp5" serverinterface="id13" />
    <exportedinterface idinterface="id5" />
  </subarchitecture>
</architecture>
